[package]
name = "oca-display"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
oca-core = { path = "../oca-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tokio = { version = "1", features = ["io-util", "net", "rt", "time"] }

[dev-dependencies]
tempfile = "3.23"
