[package]
name = "oca-git"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
fs2 = "0.4.3"
oca-core = { path = "../oca-core" }

[dev-dependencies]
tempfile = "3.23"

[target.'cfg(unix)'.dependencies]
libc = "0.2.189"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = [
    "Win32_Foundation",
    "Win32_System_Threading",
] }
