name: ci

on: push

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dtolnay/rust-toolchain@2c7215f132e9ebf062739d9130488b56d53c060c # master @ 2026-08-01
        with:
          toolchain: "1.97.1" # keep in sync with rust-toolchain.toml
      - run: cargo build --workspace
      - run: cargo test --workspace
